# Generated by Django 2.2.6 on 2019-10-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='identifier',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
